package entiendades;
// Generated 8/03/2015 02:43:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Accion generated by hbm2java
 */
@Entity
@Table(name="accion"
    ,catalog="srs"
    , uniqueConstraints = @UniqueConstraint(columnNames="nombre") 
)
public class Accion  implements java.io.Serializable {


     private Integer idaccion;
     private String nombre;
     private Set historicos = new HashSet(0);

    public Accion() {
    }

	
    public Accion(String nombre) {
        this.nombre = nombre;
    }
    public Accion(String nombre, Set historicos) {
       this.nombre = nombre;
       this.historicos = historicos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idaccion", unique=true, nullable=false)
    public Integer getIdaccion() {
        return this.idaccion;
    }
    
    public void setIdaccion(Integer idaccion) {
        this.idaccion = idaccion;
    }

    
    @Column(name="nombre", unique=true, nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="accion")
    public Set getHistoricos() {
        return this.historicos;
    }
    
    public void setHistoricos(Set historicos) {
        this.historicos = historicos;
    }




}


