package entiendades;
// Generated 8/03/2015 02:43:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlumnoHasPendienteId generated by hbm2java
 */
@Embeddable
public class AlumnoHasPendienteId  implements java.io.Serializable {


     private int usuarioIdalumno;
     private int pendienteIdpendiente;

    public AlumnoHasPendienteId() {
    }

    public AlumnoHasPendienteId(int usuarioIdalumno, int pendienteIdpendiente) {
       this.usuarioIdalumno = usuarioIdalumno;
       this.pendienteIdpendiente = pendienteIdpendiente;
    }
   


    @Column(name="usuario_idalumno", nullable=false)
    public int getUsuarioIdalumno() {
        return this.usuarioIdalumno;
    }
    
    public void setUsuarioIdalumno(int usuarioIdalumno) {
        this.usuarioIdalumno = usuarioIdalumno;
    }


    @Column(name="pendiente_idpendiente", nullable=false)
    public int getPendienteIdpendiente() {
        return this.pendienteIdpendiente;
    }
    
    public void setPendienteIdpendiente(int pendienteIdpendiente) {
        this.pendienteIdpendiente = pendienteIdpendiente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlumnoHasPendienteId) ) return false;
		 AlumnoHasPendienteId castOther = ( AlumnoHasPendienteId ) other; 
         
		 return (this.getUsuarioIdalumno()==castOther.getUsuarioIdalumno())
 && (this.getPendienteIdpendiente()==castOther.getPendienteIdpendiente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuarioIdalumno();
         result = 37 * result + this.getPendienteIdpendiente();
         return result;
   }   


}


