package entiendades;
// Generated 8/03/2015 02:43:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name="estado"
    ,catalog="srs"
    , uniqueConstraints = @UniqueConstraint(columnNames="nombre") 
)
public class Estado  implements java.io.Serializable {


     private Integer idestado;
     private String nombre;
     private Set municipios = new HashSet(0);

    public Estado() {
    }

	
    public Estado(String nombre) {
        this.nombre = nombre;
    }
    public Estado(String nombre, Set municipios) {
       this.nombre = nombre;
       this.municipios = municipios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idestado", unique=true, nullable=false)
    public Integer getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(Integer idestado) {
        this.idestado = idestado;
    }

    
    @Column(name="nombre", unique=true, nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="estado")
    public Set getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set municipios) {
        this.municipios = municipios;
    }




}


