insert into estado (nombre) values 
('Aguascalientes'),
('Baja California'),
('Baja California Sur'),
('Campeche'),
('Chiapas'),
('Chihuahua'),
('Coahuila'),
('Colima'),
('Distrito Federal'),
('Durango'),
('Estado de México'),
('Guanajuato'),
('Guerrero'),
('Hidalgo'),
('Jalisco'),
('Michoacán'),
('Morelos'),
('Nayarit'),
('Nuevo León'),
('Oaxaca'),
('Puebla'),
('Querétaro'),
('Quintana Roo'),
('San Luis Potosí'),
('Sinaloa'),
('Sonora'),
('Tabasco'),
('Tamaulipas'),
('Tlaxcala'),
('Veracruz'),
('Yucatán'),
('Zacatecas')
;
insert into municipio (nombre, idestado) values 
('Álvaro Obregón',9),
('Azcapotzalco',9),
('Benito Juárez',9),
('Coyoacán',9),
('Cuajimalpa de Morelos',9),
('Cuauhtémoc',9),
('Gustavo A. Madero',9),
('Iztacalco',9),
('Iztapalapa',9),
('La Magdalena Contreras',9),
('Miguel Hidalgo',9),
('Milpa Alta',9),
('Tláhuac',9),
('Tlalpan',9),
('Venustiano Carranza',9),
('Xochimilco',9),
('Acambay',11),
('Acolman',11),
('Aculco',11),
('Almoloya de Alquisiras',11),
('Almoloya de Juárez',11),
('Almoloya del Río',11),
('Amanalco',11),
('Amatepec',11),
('Amecameca',11),
('Apaxco',11),
('Atenco',11),
('Atizapán',11),
('Atizapán de Zaragoza',11),
('Atlacomulco',11),
('Atlautla',11),
('Axapusco',11),
('Ayapango',11),
('Calimaya',11),
('Capulhuac',11),
('Chalco',11),
('Chapa de Mota',11),
('Chapultepec',11),
('Chiautla',11),
('Chicoloapan',11),
('Chiconcuac',11),
('Chimalhuacán',11),
('Coacalco de Berriozábal',11),
('Coatepec Harinas',11),
('Cocotitlán',11),
('Coyotepec',11),
('Cuautitlán',11),
('Cuautitlán Izcalli',11),
('Donato Guerra',11),
('Ecatepec de Morelos',11),
('Ecatzingo',11),
('El Oro',11),
('Huehuetoca',11),
('Hueypoxtla',11),
('Huixquilucan',11),
('Isidro Fabela',11),
('Ixtapaluca',11),
('Ixtapan de la Sal',11),
('Ixtapan del Oro',11),
('Ixtlahuaca',11),
('Jaltenco',11),
('Jilotepec',11),
('Jilotzingo',11),
('Jiquipilco',11),
('Jocotitlán',11),
('Joquicingo',11),
('Juchitepec',11),
('La Paz',11),
('Lerma',11),
('Luvianos',11),
('Malinalco',11),
('Melchor Ocampo',11),
('Metepec',11),
('Mexicaltzingo',11),
('Morelos',11),
('Naucalpan de Juárez',11),
('Nextlalpan',11),
('Nezahualcóyotl',11),
('Nicolás Romero',11),
('Nopaltepec',11),
('Ocoyoacac',11),
('Ocuilan',11),
('Otumba',11),
('Otzoloapan',11),
('Otzolotepec',11),
('Ozumba',11),
('Papalotla',11),
('Polotitlán',11),
('Rayón',11),
('San Antonio la Isla',11),
('San Felipe del Progreso',11),
('San José del Rincón',11),
('San Martín de las Pirámides',11),
('San Mateo Atenco',11),
('San Simón de Guerrero',11),
('Santo Tomás',11),
('Soyaniquilpan de Juárez',11),
('Sultepec',11),
('Tecámac',11),
('Tejupilco',11),
('Temamatla',11),
('Temascalapa',11),
('Temascalcingo',11),
('Temascaltepec',11),
('Temoaya',11),
('Tenancingo',11),
('Tenango del Aire',11),
('Tenango del Valle',11),
('Teoloyucán',11),
('Teotihuacán',11),
('Tepetlaoxtoc',11),
('Tepetlixpa',11),
('Tepotzotlán',11),
('Tequixquiac',11),
('Texcaltitlán',11),
('Texcalyacac',11),
('Texcoco',11),
('Tezoyuca',11),
('Tianguistenco',11),
('Timilpan',11),
('Tlalmanalco',11),
('Tlalnepantla de Baz',11),
('Tlatlaya',11),
('Toluca',11),
('Tonanitla',11),
('Tonatico',11),
('Tultepec',11),
('Tultitlán',11),
('Valle de Bravo',11),
('Valle de Chalco Solidaridad',11),
('Villa de Allende',11),
('Villa del Carbón',11),
('Villa Guerrero',11),
('Villa Victoria',11),
('Xalatlaco',11),
('Xonacatlán',11),
('Zacazonapan',11),
('Zacualpan',11),
('Zinacantepec',11),
('Zumpahuacán',11),
('Zumpango',11)
;
insert into asignatura (nombre) values
('Administración de Proyectos'),
('Administración de Servicios en Red'),
('Administración Financiera'),
('Álgebra Lineal'),
('Algoritmia y Programación Estructurada'),
('Análisis de Algoritmos'),
('Análisis Fundamental de Circuitos'),
('Análisis Vectorial'),
('Análisis y Diseño Orientado a Objetos'),
('Aplicaciones  para  Comunicaciones  en  Red'),
('Aplicaciones con Microcontroladores para el Automóvil'),
('Application Development for Mobile Devices'),
('Arquitectura  de Computadoras'),
('Arquitectura de dispositivos Móviles'),
('Arquitecturas Embebidas Automotrices'),
('Artificial Intelligence'),
('Bases de Datos'),
('Bioinformatics'),
('Cálculo'),
('Comp Educt y Multim Móviles'),
('Compiladores'),
('Computer Animation'),
('Computer Graphics'),
('Comunicación Oral y Escrita'),
('Comunicaciones a Distancia'),
('Cryptography'),
('Desarrollo  de  Sistemas Distribuidos'),
('Diseño de Sistemas Digitales'),
('Distributed Data Base'),
('Economic Engineering'),
('Ecuaciones Diferenciales'),
('Electrónica Analógica'),
('Embedded Systems'),
('Estructuras de Datos'),
('Evolutionary Computing'),
('Física'),
('Fund de Com Móviles'),
('Fundamentos de Diseño Digital'),
('Fundamentos Económicos'),
('Genetic Algorithms'),
('Gestión Empresarial'),
('HT Enterprise Management'),
('Humanidades IV (ISISA)'),
('Image Analysis'),
('Ing. Soft. para Cómp. Móvil(Maestría)'),
('Ingeniería Ambiental Automotriz'),
('Ingeniería de Software'),
('Ingeniería Ética y Sociedad'),
('Instrumentación'),
('Introducción a los Microcontroladores'),
('IT Governance'),
('Liderazgo y Desarrollo Profesional'),
('Matemáticas Avanzadas  para la Ingeniería'),
('Matemáticas Discretas'),
('Métodos Cuantitativos para la Toma de Decisiones'),
('Métodos Mat. para el análisis de sist. y señales'),
('Modelos Combinatorios para Sist. de Disp Móviles'),
('Neural Networks'),
('Pattern Recognition'),
('Probabilidad y Estadística'),
('Prog. de Disp de Altas Prestaciones'),
('Prog. de Disp. Móviles (Maestría)'),
('Programación Orientada a Objetos'),
('Redes de Computadoras'),
('S.O. para Cómputo Móvil'),
('Seminario I'),
('Seminario II'),
('Seminario III'),
('Sistemas Digitales'),
('Sistemas en Tiempo Real'),
('Sistemas Operativos'),
('Tecnologías para la Web'),
('Teoría Computacional'),
('Teoria de Comunicaciones y Señales'),
('Tópicos Selectos I (ISISA)'),
('Trabajo Terminal I'),
('Trabajo Terminal II'),
('Visión Computacional'),
('Web Application Development'),
('Web Security')
;

insert into accion(nombre) values 
('modificó sus datos '),
('creó el usuario '),
('modificó el usuario '),
('eliminó el usuario '),
('creó el curso '),
('modificó el curso'),
('eliminó el curso'),
('creó un nuevo pendiente '),
('modificó el pendiente '),
('eliminó el pendiente '),
('resolvió el pendiente '),
('calificó el pendiente ')
;
