-- MySQL Script generated by MySQL Workbench
-- mar 10 mar 2015 17:04:06 CST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema srs
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `srs` ;
CREATE SCHEMA IF NOT EXISTS `srs` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `srs` ;

-- -----------------------------------------------------
-- Table `srs`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`usuario` ;

CREATE TABLE IF NOT EXISTS `srs`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `paterno` VARCHAR(60) NULL,
  `materno` VARCHAR(60) NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `rol` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `estado` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `username_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`asignatura` ;

CREATE TABLE IF NOT EXISTS `srs`.`asignatura` (
  `idasignatura` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idasignatura`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`curso` ;

CREATE TABLE IF NOT EXISTS `srs`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(50) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `idinstructor` INT NOT NULL,
  `idasignatura` INT NOT NULL,
  `estado` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idcurso`),
  INDEX `fk_curso_usuario1_idx` (`idinstructor` ASC),
  INDEX `fk_curso_asignatura1_idx` (`idasignatura` ASC),
  CONSTRAINT `fk_curso_usuario1`
    FOREIGN KEY (`idinstructor`)
    REFERENCES `srs`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_asignatura1`
    FOREIGN KEY (`idasignatura`)
    REFERENCES `srs`.`asignatura` (`idasignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`pendiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`pendiente` ;

CREATE TABLE IF NOT EXISTS `srs`.`pendiente` (
  `idpendiente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `fecha_entrega` DATE NOT NULL,
  `idcurso` INT NOT NULL,
  `estado` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idpendiente`),
  INDEX `fk_pendiente_curso_idx` (`idcurso` ASC),
  CONSTRAINT `fk_pendiente_curso`
    FOREIGN KEY (`idcurso`)
    REFERENCES `srs`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`estado` ;

CREATE TABLE IF NOT EXISTS `srs`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestado`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`municipio` ;

CREATE TABLE IF NOT EXISTS `srs`.`municipio` (
  `idmunicipio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idestado` INT NOT NULL,
  PRIMARY KEY (`idmunicipio`),
  INDEX `fk_municipio_estado1_idx` (`idestado` ASC),
  CONSTRAINT `fk_municipio_estado1`
    FOREIGN KEY (`idestado`)
    REFERENCES `srs`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`direccion` ;

CREATE TABLE IF NOT EXISTS `srs`.`direccion` (
  `iddireccion` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `no_exterior` VARCHAR(45) NULL,
  `no_interior` VARCHAR(45) NULL,
  `colonia` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(45) NOT NULL,
  `idusuario` INT NOT NULL,
  `idmunicipio` INT NOT NULL,
  PRIMARY KEY (`iddireccion`),
  INDEX `fk_direccion_usuario1_idx` (`idusuario` ASC),
  INDEX `fk_direccion_municipio1_idx` (`idmunicipio` ASC),
  CONSTRAINT `fk_direccion_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `srs`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion_municipio1`
    FOREIGN KEY (`idmunicipio`)
    REFERENCES `srs`.`municipio` (`idmunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`telefono`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`telefono` ;

CREATE TABLE IF NOT EXISTS `srs`.`telefono` (
  `idtelefono` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(15) NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idtelefono`),
  INDEX `fk_telefono_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_telefono_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `srs`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`email` ;

CREATE TABLE IF NOT EXISTS `srs`.`email` (
  `idemail` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idemail`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_email_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_email_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `srs`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`alumno_tiene_pendiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`alumno_tiene_pendiente` ;

CREATE TABLE IF NOT EXISTS `srs`.`alumno_tiene_pendiente` (
  `idatp` INT NOT NULL AUTO_INCREMENT,
  `idalumno` INT NOT NULL,
  `idpendiente` INT NOT NULL,
  `calificacion` FLOAT NOT NULL,
  `estado` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idatp`),
  INDEX `fk_usuario_has_pendiente_pendiente1_idx` (`idpendiente` ASC),
  INDEX `fk_usuario_has_pendiente_usuario1_idx` (`idalumno` ASC),
  CONSTRAINT `fk_usuario_has_pendiente_usuario1`
    FOREIGN KEY (`idalumno`)
    REFERENCES `srs`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_pendiente_pendiente1`
    FOREIGN KEY (`idpendiente`)
    REFERENCES `srs`.`pendiente` (`idpendiente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`accion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`accion` ;

CREATE TABLE IF NOT EXISTS `srs`.`accion` (
  `idaccion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idaccion`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`historico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`historico` ;

CREATE TABLE IF NOT EXISTS `srs`.`historico` (
  `idhistorico` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `detalle` VARCHAR(80) NOT NULL,
  `idaccion` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idhistorico`),
  INDEX `fk_historico_accion1_idx` (`idaccion` ASC),
  INDEX `fk_historico_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_historico_accion1`
    FOREIGN KEY (`idaccion`)
    REFERENCES `srs`.`accion` (`idaccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `srs`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `srs`.`archivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `srs`.`archivo` ;

CREATE TABLE IF NOT EXISTS `srs`.`archivo` (
  `idarchivo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(100) NOT NULL,
  `idatp` INT NOT NULL,
  PRIMARY KEY (`idarchivo`),
  UNIQUE INDEX `ubicacion_UNIQUE` (`ubicacion` ASC),
  INDEX `fk_archivo_alumno_tiene_pendiente1_idx` (`idatp` ASC),
  CONSTRAINT `fk_archivo_alumno_tiene_pendiente1`
    FOREIGN KEY (`idatp`)
    REFERENCES `srs`.`alumno_tiene_pendiente` (`idatp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
