package com.proyecto.entidades;
// Generated 8/03/2015 05:04:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Asignatura generated by hbm2java
 */
@Entity
@Table(name="asignatura"
    ,catalog="srs"
    , uniqueConstraints = @UniqueConstraint(columnNames="nombre") 
)
public class Asignatura  implements java.io.Serializable {


     private Integer idasignatura;
     private String nombre;
     private Set cursos = new HashSet(0);

    public Asignatura() {
    }

	
    public Asignatura(String nombre) {
        this.nombre = nombre;
    }
    public Asignatura(String nombre, Set cursos) {
       this.nombre = nombre;
       this.cursos = cursos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idasignatura", unique=true, nullable=false)
    public Integer getIdasignatura() {
        return this.idasignatura;
    }
    
    public void setIdasignatura(Integer idasignatura) {
        this.idasignatura = idasignatura;
    }

    
    @Column(name="nombre", unique=true, nullable=false, length=80)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="asignatura")
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


