package com.proyecto.entidades;
// Generated 8/03/2015 05:04:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="srs"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class Usuario  implements java.io.Serializable {


     private Integer iduser;
     private String name;
     private String lastname;
     private String surname;
     private String username;
     private String password;
     private int role;
     private Date date;
     private Set emails = new HashSet(0);
     private Set telefonos = new HashSet(0);
     private Set alumnoHasPendientes = new HashSet(0);
     private Set direccions = new HashSet(0);
     private Set cursos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String name, String username, String password, int role, Date date) {
        this.name = name;
        this.username = username;
        this.password = password;
        this.role = role;
        this.date = date;
    }
    public Usuario(String name, String lastname, String surname, String username, String password, int role, Date date, Set emails, Set telefonos, Set alumnoHasPendientes, Set direccions, Set cursos) {
       this.name = name;
       this.lastname = lastname;
       this.surname = surname;
       this.username = username;
       this.password = password;
       this.role = role;
       this.date = date;
       this.emails = emails;
       this.telefonos = telefonos;
       this.alumnoHasPendientes = alumnoHasPendientes;
       this.direccions = direccions;
       this.cursos = cursos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iduser", unique=true, nullable=false)
    public Integer getIduser() {
        return this.iduser;
    }
    
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    
    @Column(name="name", nullable=false, length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="lastname", length=60)
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    
    @Column(name="surname", length=60)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="username", unique=true, nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="role", nullable=false)
    public int getRole() {
        return this.role;
    }
    
    public void setRole(int role) {
        this.role = role;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=0)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getEmails() {
        return this.emails;
    }
    
    public void setEmails(Set emails) {
        this.emails = emails;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set telefonos) {
        this.telefonos = telefonos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getAlumnoHasPendientes() {
        return this.alumnoHasPendientes;
    }
    
    public void setAlumnoHasPendientes(Set alumnoHasPendientes) {
        this.alumnoHasPendientes = alumnoHasPendientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set direccions) {
        this.direccions = direccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


