package com.proyecto.model;
// Generated 09-mar-2015 16:13:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AlumnoTienePendiente generated by hbm2java
 */
@Entity
@Table(name="alumno_tiene_pendiente"
    ,catalog="srs"
)
public class AlumnoTienePendiente  implements java.io.Serializable {


     private AlumnoTienePendienteId id;
     private Pendiente pendiente;
     private Usuario usuario;
     private float calificacion;
     private Set archivos = new HashSet(0);

    public AlumnoTienePendiente() {
    }

	
    public AlumnoTienePendiente(AlumnoTienePendienteId id, Pendiente pendiente, Usuario usuario, float calificacion) {
        this.id = id;
        this.pendiente = pendiente;
        this.usuario = usuario;
        this.calificacion = calificacion;
    }
    public AlumnoTienePendiente(AlumnoTienePendienteId id, Pendiente pendiente, Usuario usuario, float calificacion, Set archivos) {
       this.id = id;
       this.pendiente = pendiente;
       this.usuario = usuario;
       this.calificacion = calificacion;
       this.archivos = archivos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idalumno", column=@Column(name="idalumno", nullable=false) ), 
        @AttributeOverride(name="idpendiente", column=@Column(name="idpendiente", nullable=false) ) } )
    public AlumnoTienePendienteId getId() {
        return this.id;
    }
    
    public void setId(AlumnoTienePendienteId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpendiente", nullable=false, insertable=false, updatable=false)
    public Pendiente getPendiente() {
        return this.pendiente;
    }
    
    public void setPendiente(Pendiente pendiente) {
        this.pendiente = pendiente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idalumno", nullable=false, insertable=false, updatable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="calificacion", nullable=false, precision=12, scale=0)
    public float getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(float calificacion) {
        this.calificacion = calificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="alumnoTienePendiente")
    public Set getArchivos() {
        return this.archivos;
    }
    
    public void setArchivos(Set archivos) {
        this.archivos = archivos;
    }




}


