package com.proyecto.model;
// Generated 09-mar-2015 16:13:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlumnoTienePendienteId generated by hbm2java
 */
@Embeddable
public class AlumnoTienePendienteId  implements java.io.Serializable {


     private int idalumno;
     private int idpendiente;

    public AlumnoTienePendienteId() {
    }

    public AlumnoTienePendienteId(int idalumno, int idpendiente) {
       this.idalumno = idalumno;
       this.idpendiente = idpendiente;
    }
   


    @Column(name="idalumno", nullable=false)
    public int getIdalumno() {
        return this.idalumno;
    }
    
    public void setIdalumno(int idalumno) {
        this.idalumno = idalumno;
    }


    @Column(name="idpendiente", nullable=false)
    public int getIdpendiente() {
        return this.idpendiente;
    }
    
    public void setIdpendiente(int idpendiente) {
        this.idpendiente = idpendiente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlumnoTienePendienteId) ) return false;
		 AlumnoTienePendienteId castOther = ( AlumnoTienePendienteId ) other; 
         
		 return (this.getIdalumno()==castOther.getIdalumno())
 && (this.getIdpendiente()==castOther.getIdpendiente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdalumno();
         result = 37 * result + this.getIdpendiente();
         return result;
   }   


}


