package com.proyecto.model;
// Generated 10-mar-2015 17:06:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AlumnoTienePendiente generated by hbm2java
 */
public class AlumnoTienePendiente  implements java.io.Serializable {


     private Integer idatp;
     private Pendiente pendiente;
     private Usuario usuario;
     private float calificacion;
     private int estado;
     private Set<Archivo> archivos = new HashSet<Archivo>(0);

    public AlumnoTienePendiente() {
    }

	
    public AlumnoTienePendiente(Pendiente pendiente, Usuario usuario, float calificacion, int estado) {
        this.pendiente = pendiente;
        this.usuario = usuario;
        this.calificacion = calificacion;
        this.estado = estado;
    }
    public AlumnoTienePendiente(Pendiente pendiente, Usuario usuario, float calificacion, int estado, Set<Archivo> archivos) {
       this.pendiente = pendiente;
       this.usuario = usuario;
       this.calificacion = calificacion;
       this.estado = estado;
       this.archivos = archivos;
    }
   
    public Integer getIdatp() {
        return this.idatp;
    }
    
    public void setIdatp(Integer idatp) {
        this.idatp = idatp;
    }
    public Pendiente getPendiente() {
        return this.pendiente;
    }
    
    public void setPendiente(Pendiente pendiente) {
        this.pendiente = pendiente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public float getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(float calificacion) {
        this.calificacion = calificacion;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set<Archivo> getArchivos() {
        return this.archivos;
    }
    
    public void setArchivos(Set<Archivo> archivos) {
        this.archivos = archivos;
    }




}


