package com.proyecto.model;
// Generated 09-mar-2015 16:13:19 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Archivo generated by hbm2java
 */
@Entity
@Table(name="archivo"
    ,catalog="srs"
    , uniqueConstraints = @UniqueConstraint(columnNames="ubicacion") 
)
public class Archivo  implements java.io.Serializable {


     private Integer idarchivo;
     private AlumnoTienePendiente alumnoTienePendiente;
     private String nombre;
     private String ubicacion;

    public Archivo() {
    }

    public Archivo(AlumnoTienePendiente alumnoTienePendiente, String nombre, String ubicacion) {
       this.alumnoTienePendiente = alumnoTienePendiente;
       this.nombre = nombre;
       this.ubicacion = ubicacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idarchivo", unique=true, nullable=false)
    public Integer getIdarchivo() {
        return this.idarchivo;
    }
    
    public void setIdarchivo(Integer idarchivo) {
        this.idarchivo = idarchivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="idalumno", referencedColumnName="idalumno", nullable=false), 
        @JoinColumn(name="idpendiente", referencedColumnName="idpendiente", nullable=false) } )
    public AlumnoTienePendiente getAlumnoTienePendiente() {
        return this.alumnoTienePendiente;
    }
    
    public void setAlumnoTienePendiente(AlumnoTienePendiente alumnoTienePendiente) {
        this.alumnoTienePendiente = alumnoTienePendiente;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="ubicacion", unique=true, nullable=false, length=100)
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }




}


