package com.proyecto.model;
// Generated 09-mar-2015 17:07:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private Integer idasignatura;
     private String nombre;
     private Set<Curso> cursos = new HashSet<Curso>(0);

    public Asignatura() {
    }

	
    public Asignatura(String nombre) {
        this.nombre = nombre;
    }
    public Asignatura(String nombre, Set<Curso> cursos) {
       this.nombre = nombre;
       this.cursos = cursos;
    }
   
    public Integer getIdasignatura() {
        return this.idasignatura;
    }
    
    public void setIdasignatura(Integer idasignatura) {
        this.idasignatura = idasignatura;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }




}


