package com.proyecto.model;
// Generated 10-mar-2015 15:08:19 by Hibernate Tools 4.3.1



/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer iddireccion;
     private Municipio municipio;
     private Usuario usuario;
     private String calle;
     private String noExterior;
     private String noInterior;
     private String colonia;
     private String cp;

    public Direccion() {
    }

	
    public Direccion(Municipio municipio, Usuario usuario, String calle, String colonia, String cp) {
        this.municipio = municipio;
        this.usuario = usuario;
        this.calle = calle;
        this.colonia = colonia;
        this.cp = cp;
    }
    public Direccion(Municipio municipio, Usuario usuario, String calle, String noExterior, String noInterior, String colonia, String cp) {
       this.municipio = municipio;
       this.usuario = usuario;
       this.calle = calle;
       this.noExterior = noExterior;
       this.noInterior = noInterior;
       this.colonia = colonia;
       this.cp = cp;
    }
   
    public Integer getIddireccion() {
        return this.iddireccion;
    }
    
    public void setIddireccion(Integer iddireccion) {
        this.iddireccion = iddireccion;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNoExterior() {
        return this.noExterior;
    }
    
    public void setNoExterior(String noExterior) {
        this.noExterior = noExterior;
    }
    public String getNoInterior() {
        return this.noInterior;
    }
    
    public void setNoInterior(String noInterior) {
        this.noInterior = noInterior;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }




}


