package com.proyecto.model;
// Generated 10-mar-2015 17:06:19 by Hibernate Tools 4.3.1



/**
 * Email generated by hbm2java
 */
public class Email  implements java.io.Serializable {


     private Integer idemail;
     private Usuario usuario;
     private String email;

    public Email() {
    }

    public Email(Usuario usuario, String email) {
       this.usuario = usuario;
       this.email = email;
    }
   
    public Integer getIdemail() {
        return this.idemail;
    }
    
    public void setIdemail(Integer idemail) {
        this.idemail = idemail;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


