package com.proyecto.model;
// Generated 8/03/2015 05:04:34 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name="email"
    ,catalog="srs"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Email  implements java.io.Serializable {


     private Integer idemail;
     private Usuario usuario;
     private String email;

    public Email() {
    }

    public Email(Usuario usuario, String email) {
       this.usuario = usuario;
       this.email = email;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idemail", unique=true, nullable=false)
    public Integer getIdemail() {
        return this.idemail;
    }
    
    public void setIdemail(Integer idemail) {
        this.idemail = idemail;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_iduser", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="email", unique=true, nullable=false, length=80)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


