package com.proyecto.model;
// Generated 09-mar-2015 17:07:35 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Historico generated by hbm2java
 */
public class Historico  implements java.io.Serializable {


     private Integer idhistorico;
     private Accion accion;
     private Usuario usuario;
     private Date fecha;
     private String detalle;

    public Historico() {
    }

    public Historico(Accion accion, Usuario usuario, Date fecha, String detalle) {
       this.accion = accion;
       this.usuario = usuario;
       this.fecha = fecha;
       this.detalle = detalle;
    }
   
    public Integer getIdhistorico() {
        return this.idhistorico;
    }
    
    public void setIdhistorico(Integer idhistorico) {
        this.idhistorico = idhistorico;
    }
    public Accion getAccion() {
        return this.accion;
    }
    
    public void setAccion(Accion accion) {
        this.accion = accion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }




}


