package com.proyecto.model;
// Generated 8/03/2015 05:04:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historico generated by hbm2java
 */
@Entity
@Table(name="historico"
    ,catalog="srs"
)
public class Historico  implements java.io.Serializable {


     private Integer idhistorico;
     private Accion accion;
     private Date fecha;
     private String detalle;

    public Historico() {
    }

    public Historico(Accion accion, Date fecha, String detalle) {
       this.accion = accion;
       this.fecha = fecha;
       this.detalle = detalle;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idhistorico", unique=true, nullable=false)
    public Integer getIdhistorico() {
        return this.idhistorico;
    }
    
    public void setIdhistorico(Integer idhistorico) {
        this.idhistorico = idhistorico;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="accion_idaccion", nullable=false)
    public Accion getAccion() {
        return this.accion;
    }
    
    public void setAccion(Accion accion) {
        this.accion = accion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=0)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="detalle", nullable=false, length=80)
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }




}


