package com.proyecto.model;
// Generated 8/03/2015 05:04:34 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MunicipioId generated by hbm2java
 */
@Embeddable
public class MunicipioId  implements java.io.Serializable {


     private int idmunicipio;
     private int estadoIdestado;

    public MunicipioId() {
    }

    public MunicipioId(int idmunicipio, int estadoIdestado) {
       this.idmunicipio = idmunicipio;
       this.estadoIdestado = estadoIdestado;
    }
   


    @Column(name="idmunicipio", nullable=false)
    public int getIdmunicipio() {
        return this.idmunicipio;
    }
    
    public void setIdmunicipio(int idmunicipio) {
        this.idmunicipio = idmunicipio;
    }


    @Column(name="estado_idestado", nullable=false)
    public int getEstadoIdestado() {
        return this.estadoIdestado;
    }
    
    public void setEstadoIdestado(int estadoIdestado) {
        this.estadoIdestado = estadoIdestado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MunicipioId) ) return false;
		 MunicipioId castOther = ( MunicipioId ) other; 
         
		 return (this.getIdmunicipio()==castOther.getIdmunicipio())
 && (this.getEstadoIdestado()==castOther.getEstadoIdestado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdmunicipio();
         result = 37 * result + this.getEstadoIdestado();
         return result;
   }   
   
}


