package com.proyecto.model;
// Generated 09-mar-2015 17:07:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private Integer idmunicipio;
     private Estado estado;
     private String nombre;
     private Set<Direccion> direccions = new HashSet<Direccion>(0);

    public Municipio() {
    }

	
    public Municipio(Estado estado, String nombre) {
        this.estado = estado;
        this.nombre = nombre;
    }
    public Municipio(Estado estado, String nombre, Set<Direccion> direccions) {
       this.estado = estado;
       this.nombre = nombre;
       this.direccions = direccions;
    }
   
    public Integer getIdmunicipio() {
        return this.idmunicipio;
    }
    
    public void setIdmunicipio(Integer idmunicipio) {
        this.idmunicipio = idmunicipio;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Direccion> getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set<Direccion> direccions) {
        this.direccions = direccions;
    }




}


