package com.proyecto.model;
// Generated 09-mar-2015 16:13:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name="municipio"
    ,catalog="srs"
)
public class Municipio  implements java.io.Serializable {


     private Integer idmunicipio;
     private Estado estado;
     private String nombre;
     private Set direccions = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(Estado estado, String nombre) {
        this.estado = estado;
        this.nombre = nombre;
    }
    public Municipio(Estado estado, String nombre, Set direccions) {
       this.estado = estado;
       this.nombre = nombre;
       this.direccions = direccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmunicipio", unique=true, nullable=false)
    public Integer getIdmunicipio() {
        return this.idmunicipio;
    }
    
    public void setIdmunicipio(Integer idmunicipio) {
        this.idmunicipio = idmunicipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idestado", nullable=false)
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="municipio")
    public Set getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set direccions) {
        this.direccions = direccions;
    }




}


