package com.proyecto.model;
// Generated 09-mar-2015 17:07:35 by Hibernate Tools 4.3.1



/**
 * Telefono generated by hbm2java
 */
public class Telefono  implements java.io.Serializable {


     private Integer idtelefono;
     private Usuario usuario;
     private String telefono;

    public Telefono() {
    }

    public Telefono(Usuario usuario, String telefono) {
       this.usuario = usuario;
       this.telefono = telefono;
    }
   
    public Integer getIdtelefono() {
        return this.idtelefono;
    }
    
    public void setIdtelefono(Integer idtelefono) {
        this.idtelefono = idtelefono;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


