package com.proyecto.model;
// Generated 10-mar-2015 15:08:19 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private String nombre;
     private String paterno;
     private String materno;
     private String usuario;
     private String clave;
     private int rol;
     private Date fecha;
     private byte estado;
     private Set<Email> emails = new HashSet<Email>(0);
     private Set<Telefono> telefonos = new HashSet<Telefono>(0);
     private Set<Historico> historicos = new HashSet<Historico>(0);
     private Set<Curso> cursos = new HashSet<Curso>(0);
     private Set<AlumnoTienePendiente> alumnoTienePendientes = new HashSet<AlumnoTienePendiente>(0);
     private Set<Direccion> direccions = new HashSet<Direccion>(0);

    public Usuario() {
    }

	
    public Usuario(String nombre, String usuario, String clave, int rol, Date fecha, byte estado) {
        this.nombre = nombre;
        this.usuario = usuario;
        this.clave = clave;
        this.rol = rol;
        this.fecha = fecha;
        this.estado = estado;
    }
    public Usuario(String nombre, String paterno, String materno, String usuario, String clave, int rol, Date fecha, byte estado, Set<Email> emails, Set<Telefono> telefonos, Set<Historico> historicos, Set<Curso> cursos, Set<AlumnoTienePendiente> alumnoTienePendientes, Set<Direccion> direccions) {
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.usuario = usuario;
       this.clave = clave;
       this.rol = rol;
       this.fecha = fecha;
       this.estado = estado;
       this.emails = emails;
       this.telefonos = telefonos;
       this.historicos = historicos;
       this.cursos = cursos;
       this.alumnoTienePendientes = alumnoTienePendientes;
       this.direccions = direccions;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public int getRol() {
        return this.rol;
    }
    
    public void setRol(int rol) {
        this.rol = rol;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }
    public Set<Email> getEmails() {
        return this.emails;
    }
    
    public void setEmails(Set<Email> emails) {
        this.emails = emails;
    }
    public Set<Telefono> getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set<Telefono> telefonos) {
        this.telefonos = telefonos;
    }
    public Set<Historico> getHistoricos() {
        return this.historicos;
    }
    
    public void setHistoricos(Set<Historico> historicos) {
        this.historicos = historicos;
    }
    public Set<Curso> getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set<Curso> cursos) {
        this.cursos = cursos;
    }
    public Set<AlumnoTienePendiente> getAlumnoTienePendientes() {
        return this.alumnoTienePendientes;
    }
    
    public void setAlumnoTienePendientes(Set<AlumnoTienePendiente> alumnoTienePendientes) {
        this.alumnoTienePendientes = alumnoTienePendientes;
    }
    public Set<Direccion> getDireccions() {
        return this.direccions;
    }
    
    public void setDireccions(Set<Direccion> direccions) {
        this.direccions = direccions;
    }




}


